"""create dicom_series table

Revision ID: 072e22303d3e
Revises: 872552013a66
Create Date: 2024-06-08 18:50:31.652963

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "072e22303d3e"
down_revision: Union[str, None] = "872552013a66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicom_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("StudyInstanceUID", sa.String()),
        sa.Column("SeriesInstanceUID", sa.String()),
        sa.Column("Modality", sa.String()),
        sa.Column("BodyPartExamined", sa.String()),
        sa.Column("PatientID", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["PatientID"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


pass


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dicom_series")
    pass
    # ### end Alembic commands ###
