"""add phone number and last login field

Revision ID: 872552013a66
Revises: a3afeda948e8
Create Date: 2024-06-03 17:05:20.652053

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "872552013a66"
down_revision: Union[str, None] = "a3afeda948e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("phone_number", sa.String(), nullable=False)
    )
    op.add_column(
        "user_account",
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "last_login")
    op.drop_column("user_account", "phone_number")
    # ### end Alembic commands ###
